services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products-api
    ports:
      - 5432:5432
  redis:
    image: 'redis:alpine'
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'
