services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products-api
    ports:
      - 5432:5432
    volumes:
      - products-api-postgres:/var/lib/postgresql/data

volumes:
  products-api-postgres:
    driver: local
